name: Project-Checks

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # pnpm on github action 
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10 # also can use the same version that have on your pc

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm' # if use pnpm cache then project build more faster

      - name: Install Dependencies
        run: pnpm install

      - name: Prisma Generate
        run: pnpm exec prisma generate

      - name: Run Build
        run: pnpm run build
        env:
          # it need for the action robot chekcing thats why alawys give fake credentials.
          DATABASE_URL: "postgresql://xplorekamrul:randompassword@localhost:5432/mydb?schema=public"
          NEXTAUTH_SECRET: "xplorekamrul-secret-for-build-purposes"
          NEXT_PUBLIC_API_URL: "http://localhost:3000"