name: Project-Checks

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with: 
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        # We provide the DATABASE_URL here because pnpm install 
        # automatically runs 'prisma generate' via postinstall
        run: pnpm install
        env:
          DATABASE_URL: "postgresql://xplorekamrul:randompassword@localhost:5432/mydb?schema=public"

      - name: Run Build
        run: pnpm run build
        env:
          DATABASE_URL: "postgresql://xplorekamrul:randompassword@localhost:5432/mydb?schema=public"
          NEXTAUTH_SECRET: "xplorekamrul-secret-for-build-purposes"
          NEXT_PUBLIC_API_URL: "http://localhost:3000"